spring:
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver

      #url: jdbc:mysql://39.104.186.34:3306/zydb2018?characterEncoding=utf8
      #username: root
      #password: zhiyou2018
      #whrzyDB2019
      url: jdbc:mysql://localhost:3306/whrzyDB2019?characterEncoding=utf8
      username: root
      password: 123456

      #最大活跃数
      maxActive: 20
      #初始化数量
      initialSize: 1
      #最大连接等待超时时间
      maxWait: 60000
      #打开PSCache，并且指定每个连接PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #json中不显示null的值
    default-property-inclusion: non_null

server:
  context-path: /whrzy
  port: 9090

#自定义的属性和值zhiyou2018
appWeb:
  pageSize: 300
  templates:  templates                                #模板文件保存的目录
  uploadFile: uploadFiles                              #用户上传的其他文件（例如年检报告，事故记录，电梯知识库）存放的目录
  appFile:    appFiles                                  #App上传的文件目录
  tempFile:   tempFiles                                 #数据导入时，临时保存的文件


  spring:
    mvc:
      static-path-pattern: /**
    resources:
      static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
        classpath:/static/static/,classpath:/static/,classpath:/public/,file:${web.upload-path},file:./static/pic/





